- hosts: frontends
  gather_facts: false
  tasks:
  - name: Use Uri module for wrting smoke test.
    uri:
      url: "http://localhost/index.html"
      #return_content: yes
      return_content: true
    register: webpage
    #failed_when: "'Ansible has done its job ' not in webpage.content"
    failed_when:
    - "'Ansible has done its job' not in webpage.content"
    - webpage.status != 200
#  - name: Fail if 'Ansible has done its job' is not in the page content
